name: Publish to npm on tag
on:
  push:
    tags:
      - 'v*.*.*'        #ex: v1.2.3
      - 'v*.*.*-beta.*' #ex: v1.2.3-beta.1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Set package.json version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          npm version $VERSION --no-git-tag-version

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          if [[ $VERSION == *"-beta"* ]]; then
            npm publish --tag beta --access public
          else
            npm publish --tag latest --access public
          fi
